### ISSUE TITLE
Followed the tutorial; app is crashing during registration every time

### ISSUE THREAD

**Issue by m1baldwin** [DJI-Mobile-SDK-Tutorials/Android-SimulatorDemo#10]
I have been trying to follow the tutorial here: https://developer.dji.com/mobile-sdk/documentation/android-tutorials/SimulatorDemo.html to test out the basic simulator functionality on an android app. I am using a DJI mavic 2 pro and smart controller. 

I can program the app onto the smart controller, however whenever I try to start the simulator demo, the app crashes. I am connected to wifi with access to the internet, and I have previously been able to complete this tutorial: https://developer.dji.com/mobile-sdk/documentation/quick-start/index.html#run-the-sample-app

What is the advised way to troubleshoot? I am new to android development so any advice is appreciated!

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/48123'>Zendesk ticket #48123</a>:<br><br>Dear Client
Thank you for contacting DJI.

This demo hasn't been update for a long time, we suggest you use the Sample app's simulator demo.
Link：https://github.com/dji-sdk/Mobile-SDK-Android/blob/master/Sample%20Code/app/src/main/java/com/dji/sdk/sample/demo/flightcontroller/VirtualStickView.java

Hopefully our solution can help you.
Kindly Regards,
DJI Developer Support
<br><p><em><small>°°°</small></em></p>

**Comment by m1baldwin** [comment]
Thanks; I figured it might be better to go with a more recent demo. Let's close this issue.
