### ISSUE TITLE
typo in documentation

### ISSUE THREAD

**Issue by Li-Yanzhi** [DJI-Mobile-SDK-Tutorials/Android-SimulatorDemo#3]
In Simulator Tutorial (https://developer.dji.com/cn/mobile-sdk/documentation/android-tutorials/SimulatorDemo.html),  the word "**valures**" in sentence of "...we multiply by using the verticalJoyControlMaxSpeed and yawJoyControlMaxSpeed **valures** to..." is typo of "values"?

Another issue, in section "Implementing Virtual Stick Control",  In the paragraph of 

> "2. Get the maximum velocity of vertical control and maximum angle velocity of Virtual Stick, then store them to verticalJoyControlMaxSpeed and yawJoyControlMaxSpeed variables. Since the value of pX is between -1 (left) and 1 (right), the value of pY is between -1 (down) and 1 (up), we multiply by using the verticalJoyControlMaxSpeed and yawJoyControlMaxSpeed valures to update the mYaw and mThrottle data. Here we take Mode 2(American mode) of remote controller as example."

It's supposed to describe the code in **mScreenJoystickLeft.setJoystickListener**,  not the next section of **mScreenJoystickRight.setJoystickListener**.

**Comment by oliverou** [comment]
Hi @Li-Yanzhi , thanks for your feedbacks! We have fixed the issues and updated the Simulator Tutorial on the DJI developer website, please check it, thanks!

**Comment by Li-Yanzhi** [comment]
Thanks, it's OK now.
