### ISSUE TITLE
Question about Simulator demo

### ISSUE THREAD

**Issue by phongnhhn92** [DJI-Mobile-SDK-Tutorials/Android-SimulatorDemo#4]
Hello guys,
I have a question after reading the tutorial website. From what I understand, this Android simulator app have a virtual stick and using this app, we can control the drone to move as we wanted. So my question is that when we press Start Simulator button, is that the same with connecting to the drone ? Or do I need to connect the drone to my smartphone using DJI GO app first then I can use this simulator demo app ? Also, what happens if the Remote controller and the simulator app which both have joysticks so which one will be disable ? 
I am sorry if I have too much question, hope someone can help me to understand this. Thanks !

**Comment by oliverou** [comment]
Hi @phongnhhn92, this Android SimulatorDemo has a tutorial for it: <http://developer.dji.com/mobile-sdk/documentation/android-tutorials/SimulatorDemo.html>, it should help to resolve your problems. Please check it.
