### ISSUE TITLE
Question about Simulation Demo

### ISSUE THREAD

**Issue by Asendo316** [DJI-Mobile-SDK-Tutorials/Android-SimulatorDemo#7]
Hello I have just implemented and tested the simulation demo in my DJI simulator.
However, I wanted to verify is this demo would allow me fly the drone outside the simulator with the virtual joystics

**Comment by dji-dev** [comment]
Public comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/32093'>Zendesk ticket #32093</a>:<br><br>Dear Customer,

Thank you for contacting DJI.
Yes, this demo also can work in a real flight.

Thanks,

Luce Luo
DJI Dev Team

**Comment by Asendo316** [comment]
Hello Thank you for your prompt response. 
How do i set it up for real flight please?

**Comment by dji-dev** [comment]
Public comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/32093'>Zendesk ticket #32093</a>:<br><br>Dear Customer,

Thank you for contacting DJI.
You can run it without starting the simulator and then it will work.

Thanks,

Luce Luo
DJI Dev Team
