### ISSUE TITLE
Enable virtual stick not responding most of the time.

### ISSUE THREAD

**Issue by vivekgabadiya** [DJI-Mobile-SDK-Tutorials/Android-SimulatorDemo#8]
After connecting mavic pro 2 it is showing connected and also showing name of the drone in the title but once I click on enable virtual stick it is not showing any toast message i.e. no error message and no success message. I have to connect and disconnect it multiple times to make it work. Please help me with this.

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/32937'>Zendesk ticket #32937</a>:<br><br>Dear Client
Thank you for contacting DJI.

Sorry, we havn't reproduced your issue on our side. Could you provide more details about how to reproduce your issue please?

Hopefully our solution can help you.
Kindly Regards,
DJI Developer Support

**Comment by vivekgabadiya** [comment]
It seems when we launch the app most of the time aircraft got disconnected so enable virtual stick not responding but once we minimize the app and open again it will try to connect again with aircraft and once it is connected properly then virtual stick click is also working. 
The problem is we are not able to connect with aircraft properly after launching the app most of the time.

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/32937'>Zendesk ticket #32937</a>:<br><br>Dear Client
Thank you for contacting DJI.

That's weird, please make sure your mobile phone has a stable network conditions during usage.

Hopefully our solution can help you.
Kindly Regards,
DJI Developer Support
